### ISSUE TITLE
Share my donation? (Twitter)

### ISSUE THREAD

**Issue by katzcaban** [commons-stack/tech-dapp#104]
Option to share my donation transaction on social platforms? Did not see this option. (Twitter, etc..)

**Comment by sponnet** [comment]
- [ ]  fix twitter + telegram  button to look like figma
- [ ] show the right donated amount
- [ ] add confetti here !!!  green yellow with a touch of blue and white !

**Comment by GriffGreen** [comment]
I've just become a member of Commons Stack's Swiss Association! 🎉🌍🌌🎩🥂 Join us: commonsstack.org/apply


https://github.com/commons-stack/iteration0/issues/287

**Comment by GriffGreen** [comment]
I've just become a member of Commons Stack's Swiss Association! 🎉🌍🌌🎩🥂 Join us: commonsstack.org/apply
