### ISSUE TITLE
Membership Tab in upper left

### ISSUE THREAD

**Issue by katzcaban** [commons-stack/tech-dapp#106]
Does nothing when you click on this. Upper left of page next to "help".

![image](https://user-images.githubusercontent.com/73135591/103857076-66278e80-507b-11eb-81b2-92d41d9b00d9.png)

**Comment by katzcaban** [comment]
Should this perhaps take user to a link in which they can receive information on how to become a Member of Trusted Seed?

**Comment by sponnet** [comment]
- [ ] get content to put there (a faq)
- [ ] add a component Faq.js
- [ ] add it to the pages/index.js

# FAQ

introduction - what does this thing do ???

## other questions

If you have any other questions send us a mail on ....

**Comment by sponnet** [comment]
for the time being - comment out the 2 tabs until we have FAQ text
