### ISSUE TITLE
CSTK Score-must be refreshed after donating to view

### ISSUE THREAD

**Issue by katzcaban** [commons-stack/tech-dapp#107]
In order to view your CSTK score, you must refresh the whole page in order to view score. This can come off as confusing if there is no warning to do so in order to view score. Does not apply the score automatically.

**Comment by katzcaban** [comment]
Should the score just appear after donating? It certainly would be sexier. Maybe this isn't important...or maybe it is.

**Comment by sponnet** [comment]
create a setInterval  and dispatch 'GET_BALANCES_FOR_ADDRESS' every  30s
