### ISSUE TITLE
Member of Trusted Seed alert

### ISSUE THREAD

**Issue by katzcaban** [commons-stack/tech-dapp#110]
After donating, I refreshed the page a couple times. Twice It stated I wasn't a member of the TS. It eventually understood I was and allowed me access to donate again. Why is this? Maybe something we can iron out.

**Comment by tamarandom** [comment]
Hey @katzcaban ! Labelling as bug. Might have already been fixed though we will very quickly find out in our next round of user testing.

**Comment by tamarandom** [comment]
Fixed. No reoccurrence logged yet.
