### ISSUE TITLE
Window size makes it hare to accept Terms and Statutes

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/tech-dapp#124]
The button to move to the next page is not visible in the window and I can't scroll

<img width="943" alt="Screen Shot 2021-01-20 at 7 21 23 PM" src="https://user-images.githubusercontent.com/14945613/105257614-7023b400-5b88-11eb-895b-8feae5f93640.png">

**Comment by tamarandom** [comment]
No OK button = Not OK ;)

**Comment by mendesfabio** [comment]
> No OK button = Not OK ;)
> 
> @mendesfabio You think you can pick this one up?

Fixed #153!
