### ISSUE TITLE
ADD the new pretty things : The approve and payment waiting screens could be stylized and more beautiful

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/tech-dapp#127]
![Screen Shot 2021-01-18 at 5.57.26 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/839daac3-8484-4d93-9b9c-421e3e1dfee1)

**Comment by markoprljic** [comment]
Created new modals.

<img width="1392" alt="Image 2021-01-22 at 1 13 45 pm" src="https://user-images.githubusercontent.com/5704285/105489555-b295df80-5cb3-11eb-938f-a9566cec5446.png">

@sponnet Using Lottie loading animation https://lottiefiles.com/9914-loading-success-fail-spinner-stroke-update

**Comment by sponnet** [comment]
Nice one @markoprljic ! Let's add these beauties !
