### ISSUE TITLE
The CSTK Score should be 0 until the person has paid their Dues

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/tech-dapp#128]
While they may have tokens now... they don't actually have a membership score until they have paid the 450 DAI... they have a pending score, then they get their new tokens and their old tokens as the score. See the figma.

https://www.figma.com/file/pSFJQppLaduz91LI8AYIHG/The-Commons-Stack?node-id=1451%3A1489

![Screen Shot 2021-01-20 at 9.14.43 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/9b0647d9-4290-48e5-82d7-f862dc50a7d9)

**Comment by sponnet** [comment]
Any idea how this would be implemented with the current smart contracts ? All I can see now is their CSTK balance.

**Comment by tamarandom** [comment]
If membership dues paid then the score shows <your CSTK balance plus your pending balance> AND the the minimum contribution is 1 DAI.

If membership dues NOT paid then you see 0 CSTK score and the pending score is showed in the lower left box AND minimum balance is 450 DAI.

**Comment by aminlatifi** [comment]
Balance api is ready by this [PR](https://github.com/commons-stack/tech-dapp-api/pull/5), it provides how much of user donations events is reached to minter after a block number we define.
