### ISSUE TITLE
Edits to CSTK Token Dapp UI

### ISSUE THREAD

**Issue by Jeff-Emmett** [commons-stack/tech-dapp#132]
Great work on the dapp all! Just a few edits I would suggest at the bottom of the dapp, as highlighted in the image below.

1. Update "FOR YOUR CONTRIBUTION YOU WILL ALSO RECEIVE:" to **"Your CSTK Score enables:"**

2. Update "Governance Rights" to **"Participation in Community Governance"**

3. Update "Access to Future ABC Hatch Phases" to **"Access to Future Commons Hatches"**

4. Update "Membership in Swiss Commons Stack Associations" to **"Membership in Commons Stack Swiss Association"**

![image](https://user-images.githubusercontent.com/46964190/105651544-2a673400-5e85-11eb-8cdb-951d7d6d0d10.png)

**Comment by tamarandom** [comment]
@MerlinEgalite Can you take this one on?
