### ISSUE TITLE
Membership Terms signature 

### ISSUE THREAD

**Issue by liviade1** [commons-stack/tech-dapp#133]
"sign terms and conditions" and "sign statutes" appear to be signed already. I think it would be nice to have to click on them to sign, it seems sneaky somehow that they are already clicked 😬
<img width="322" alt="Screen Shot 2021-01-25 at 9 08 11 PM" src="https://user-images.githubusercontent.com/52081044/105781505-78e20480-5f51-11eb-8871-e5340d1db3b5.png">

**Comment by tamarandom** [comment]
@liviade1 this is the current flow. You might have gone back to the page after you agreed already.
