### ISSUE TITLE
I want to contribute - suggested amount 

### ISSUE THREAD

**Issue by liviade1** [commons-stack/tech-dapp#134]
- I was expecting the suggested value to be 450 instead of 500. 
- the app allows me to selected a value under 450. 
I have 2 suggestions: 
1. to lock the value on 450 and if anyone tries lowering, a pop up could come up talking about the scholarship. 
2. we could have two lines. One showing how much is the max you can contribute based on the CSTK as a suggestion that you can make the max contribution in one click, and another one under with the minimum you can contribute which is 450.
<img width="665" alt="Screen Shot 2021-01-25 at 9 16 03 PM" src="https://user-images.githubusercontent.com/52081044/105782184-c9a62d00-5f52-11eb-84fe-a2dcd265ef0c.png">

**Comment by tamarandom** [comment]
Hey @liviade1 Way to QA!! You bring up another point though :  The membership dues are 450. So if they pay a lower sum of dues then they should not become a member of the Swiss Association.

+ @GriffGreen 

There are open issues for the other two but I will leave this open to address submitting < 450. 

For the default sum:  #148 (going to be 900 to include 1 scholarship, can be dropped to 450) 
For the scholarship info : #151

**Comment by tamarandom** [comment]
Addressed in #128.
