### ISSUE TITLE
Text for the options under "FOR YOUR CONTRIBUTION YOU WILL ALSO RECEIVE:" is misaligned.

### ISSUE THREAD

**Issue by knobsdao** [commons-stack/tech-dapp#136]
Ideal:
Governance Rights | Access to Future ABC Hatch Phases | Membership in Swiss Commons Stack Associations

What the current feels like: 
Membership in Swiss Commons Stack Association

Access to Future ABC Hatch Phases

Governance Rights

**Comment by tamarandom** [comment]
Hey @knobsdao ! @Jeff-Emmett addressed the same in #132. Closing yours. ;-)
