### ISSUE TITLE
Instructions/link to add CSTK to wallet on xDAI after contributing

### ISSUE THREAD

**Issue by knobsdao** [commons-stack/tech-dapp#138]
It is super awesome to see the Score updated right after contributing! Also checked my wallet on xDAI and saw it there. A great nice-to-have would be a link for users to know how to have it displayed in their wallets.

**Comment by tamarandom** [comment]
@knobsdao Yep, good idea. Tagged nice to have.

**Comment by aminlatifi** [comment]
![image](https://user-images.githubusercontent.com/5684607/107563688-a045fc00-6bf6-11eb-8021-3515b82786c0.png)

**Comment by aminlatifi** [comment]
https://faucet.1hive.org/#/

**Comment by tamarandom** [comment]
For reference : https://github.com/MetaMask/Add-Token

**Comment by tamarandom** [comment]
Hey @markoprljic Assigning to you to decide where to put the fox on the page ;)

**Comment by markoprljic** [comment]
Added link on Success modal and in sidebar under the wallet.

<img width="559" alt="Image 2021-02-11 at 1 05 16 pm" src="https://user-images.githubusercontent.com/5704285/107634461-d2dd0c80-6c69-11eb-844e-db279a89677d.png">

<img width="527" alt="Image 2021-02-11 at 1 05 04 pm" src="https://user-images.githubusercontent.com/5704285/107634478-d8d2ed80-6c69-11eb-85c1-fc1525e71742.png">
