### ISSUE TITLE
"Membership in Swiss Commons Stack AssociationS" is in plural

### ISSUE THREAD

**Issue by knobsdao** [commons-stack/tech-dapp#139]
Shouldn't it be "Association"? Otherwise, I'm inclined to wonder about the multitude of associations I'm joining.

**Comment by tamarandom** [comment]
Hey @knobsdao Uh-ohs! Where does it say that!? It might have already been fixed. Any chance you remember where you saw this?

**Comment by knobsdao** [comment]
![fdddd.jpg](https://images.zenhubusercontent.com/5f9b35816d32216fe3d07c7e/d67863e4-a9c2-4d6c-b366-ef349f511d67)

**Comment by tamarandom** [comment]
Fixed.
