### ISSUE TITLE
Desired Actions after contributing are unclear

### ISSUE THREAD

**Issue by knobsdao** [commons-stack/tech-dapp#140]
Some CTAs after making a contribution (besides Tweeting/TG) would kill it. Maybe under the benefits. Otherwise, it feels like an orphan space with no desired actions and no reason to come back to.

**Comment by tamarandom** [comment]
Hey @knobsdao What are you thinking about in terms of the CTA!? Join us on discord!? Let's get specific so we can execute it.

**Comment by knobsdao** [comment]
Hey @knobsdao What are you thinking about in terms of the CTA!? Join us on discord!? Let's get specific so we can execute.

Depends on strategy. A dedicated Discord channel may be the best option. Pinning @krisjpi.

**Comment by tamarandom** [comment]
Dupe of #104
