### ISSUE TITLE
Set Default to 900 instead of 500

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/tech-dapp#148]
The default is currently set to 500 DAI and it's easier to click yes than to change it. 
One idea is to set the default to 900 DAI with wording that that sum includes a scholarship for a community member that is unable to afford a full donation. 

Update : Issue #151 contains the functionality to show how many scholarships would be covered and the wording to use.

**Comment by tamarandom** [comment]
@MerlinEgalite can you take this one on?

**Comment by MerlinEgalite** [comment]
What is the wording you want to add and where do you to put it?

**Comment by tamarandom** [comment]
The wording is in #151, which is tied to this one.
