### ISSUE TITLE
Main Button after paying dues needs to be relabeled

### ISSUE THREAD

**Issue by krisjpi** [commons-stack/tech-dapp#150]
Adding additional DAI is considered membership fees paid, not a contribution. Button should be relabeled for accuracy. "Contribution" should also be changed to this wherever it exists. (ex. For your contribution you will receive)

**Comment by tamarandom** [comment]
@MerlinEgalite Can you take this one on too ;) 

@krisjpi I can't find the button of which you speak. ;) Any change you have a screen grab? (Button should be relabeled for accuracy.)

I did find this though which we can change to DUES. 

For the second part, change the wording to : 
"FOR YOUR DUES YOU WILL ALSO RECEIVE: "

![Screen Shot 2021-02-02 at 3.45.22 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/a136c286-e86d-4539-9922-e2bcf0f109f3)

**Comment by krisjpi** [comment]
![Contribution Button](https://user-images.githubusercontent.com/41163644/106798196-83b42d80-6612-11eb-914c-8d34d69c5e55.png)
This is the button that needs relabeling!
