### ISSUE TITLE
Divide the amount selected by 450 (and round down) and make a tool tip for "this pays for X Scholarships"

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/tech-dapp#151]
So really the logic would be: 

Divide by 450 and subtract 1... If >1 show a tool tip that says "this pays for X scholarships"

<img width="282" alt="Screen Shot 2021-01-30 at 2 47 29 PM" src="https://user-images.githubusercontent.com/14945613/106366526-c0470700-633c-11eb-8155-afad9244b190.png">

**Comment by tamarandom** [comment]
@MerlinEgalite do you think you can take this on? 

The idea is to show how many scholarships the contribution - above the initial donation of 450 - will cover. 
So a donation of 1K will cover 1 scholarship. A donation of 2K will cover 3 scholarships. 
We should not show "0 scholarships covered" ;) 

Wording : 
"In addition to your membership dues, this will fund X scholarships!"
