### ISSUE TITLE
Change wording for "access to future ABC Hatch Phases"

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/tech-dapp#155]
![Screen Shot 2021-02-03 at 2.57.39 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/af05a3c4-cb98-45da-9e3e-b6e76e1db760)

Change it to: Potential Access to Many Future Hatches

**Comment by tamarandom** [comment]
@GriffGreen I'm looking at #132 and the language of "Access to Future Commons Hatches". It seems to work be more clear than "ABC Hatch Phases". Do we commit to the "commons" wording and use "Potential access future Commons hatches"?
