### ISSUE TITLE
After DAI balance has been approved nothing happens

### ISSUE THREAD

**Issue by markoprljic** [commons-stack/tech-dapp#158]
After DAI balance has been approved I'm still seeing the Loading modal saying "Approving DAI balance".
As a user I have the option to close the modal, but I'm not sure I should do that, what happens afterwards?
The modal should automatically udapte the state and offer me next step in the process.

<img width="766" alt="Image 2021-02-07 at 11 59 44 am" src="https://user-images.githubusercontent.com/5704285/107144562-42868b00-693c-11eb-82b5-f6781d11fa7b.png">

**Comment by tamarandom** [comment]
Possible condition: 
-whitelisted 
-no allowance / not enough allowance

**Comment by GriffGreen** [comment]
REMOVE ALLOWANCES!
https://tac.dappstar.io/

**Comment by tamarandom** [comment]
Update : 

Special edge case. 

When an address has an allowance < 450 DAI with Giveth, then this error is shown. 
This will only happen to Giveth friends. Should not be blocking release of dApp.

**Comment by aminlatifi** [comment]
Making allowance zero if it's not enough was already implemented. I tested it and it works as expected.

**Comment by tamarandom** [comment]
Great @aminlatifi ! So, we close this.
