### ISSUE TITLE
Can't get past signing the terms ith a non whitelisted address

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/tech-dapp#169]
![Screen Shot 2021-02-10 at 2.14.38 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/473ab254-684e-4b35-9eda-08c7324db129)

![Screen Shot 2021-02-10 at 2.14.31 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/dee697f9-3c24-472e-ac1a-4b2edb499445)

**Comment by tamarandom** [comment]
Hey @sponnet ! Any word on this one!?

**Comment by sponnet** [comment]
I believe this is fixed with the new API deploy... The IPFS hashes of the T&C (in the develop branch) didn't match , but I think they do now.

**Comment by tamarandom** [comment]
That's great, @sponnet !

@GriffGreen do you think we can test this? We'd need someone with a non-whitelisted address.  Or do we close!?

**Comment by tamarandom** [comment]
Closing.
