### ISSUE TITLE
Audit the CSTK transfers to ensure they match the donations collected

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/tech-dapp#170]
CSTK Transfers happen here: https://blockscout.com/poa/xdai/address/0xc4fbE68522ba81a28879763C3eE33e08b13c499E/logs

This is ALL Token transfers... some of which are burn events or praise dishing so watch out...

**Comment by GriffGreen** [comment]
Here is where to get the donations
https://beta.giveth.io/campaigns/5feb2ca1dae3134bd0166dd6

![Screen Shot 2021-02-10 at 2.48.37 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/7e2b326f-3a4f-429d-9de0-7774057c29fb)

Or you can print it out via the fund history

**Comment by aminlatifi** [comment]
> CSTK Transfers happen here: https://blockscout.com/poa/xdai/address/0xc4fbE68522ba81a28879763C3eE33e08b13c499E/logs
> 
> This is ALL Token transfers... some of which are burn events or praise dishing so watch out...

This link doesn't include all token transfers, for instance this tx https://blockscout.com/poa/xdai/tx/0x4e402802cc2894d912494e1bce5da29ff00fbe8ed857413f96c46e012c240efd/token-transfers caused minting 12 CSTK but there is no sign of that in the above link

**Comment by aminlatifi** [comment]
These are donations did not cause minting:
```
"Campaign Received Donation","https://etherscan.io/tx/0x36f656a3e819f4d94b9656498cc38df45e1f03a3e26097998548a891e6fdf703" // Donated before deploy block 1 DAI
"Campaign Received Donation","https://etherscan.io/tx/0x8e4f2d5212bc374b3832eb8a15574644638c9923be8d968262c1c89fe0ce18cc" // Donated before deploy block 200 DAI
"Campaign Received Donation","https://etherscan.io/tx/0xfaacebf5ca5ffe937b8ad6672ce6c8b6eb8953e1dd81b76578e3c811da97e840" // Donated before deploy block 1 DAI
"Campaign Received Donation","https://etherscan.io/tx/0xef612283a9eff7386a8e3f27723d09261f56c616280950b3fea0f9a8959bcfa1" // Minter throws error 1 DAI
"Campaign Received Donation","https://etherscan.io/tx/0xf2fcdc68f7fe9cdf067c883c05da794d2ab703506a00a41ff4f6f564c90e97f8" // Minter throws error 450 DAI
"Campaign Received Donation","https://etherscan.io/tx/0xacb419116ccc5d6c52b5c59801611f8a12cb491f7f99a6f56e499a5dae68be18" // It's ETH
```

**Comment by aminlatifi** [comment]
#175

**Comment by aminlatifi** [comment]
> These are donations did not cause minting:
> 
> Transction Hash	Reason
> https://etherscan.io/tx/0x36f656a3e819f4d94b9656498cc38df45e1f03a3e26097998548a891e6fdf703	Donated before deploy block 1 DAI
> https://etherscan.io/tx/0x8e4f2d5212bc374b3832eb8a15574644638c9923be8d968262c1c89fe0ce18cc	Donated before deploy block 200 DAI
> https://etherscan.io/tx/0xfaacebf5ca5ffe937b8ad6672ce6c8b6eb8953e1dd81b76578e3c811da97e840	Donated before deploy block 1 DAI
> https://etherscan.io/tx/0xef612283a9eff7386a8e3f27723d09261f56c616280950b3fea0f9a8959bcfa1	Minter throws error 1 DAI
> https://etherscan.io/tx/0xf2fcdc68f7fe9cdf067c883c05da794d2ab703506a00a41ff4f6f564c90e97f8	Minter throws error 450 DAI
> https://etherscan.io/tx/0xacb419116ccc5d6c52b5c59801611f8a12cb491f7f99a6f56e499a5dae68be18	It's ETH

@GriffGreen It's what you want?

**Comment by tamarandom** [comment]
Update : Amin confirmed actions. Closed!
