### ISSUE TITLE
Error message "You are not a member of the Trusted Seed"

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/tech-dapp#173]
One of the TEC Stewards is not able to complete his application. 
Address : 0x7d547666209755FB833f9B37EebEa38eBF513Abb
(@GriffGreen I don't know if this is helpful or not but I do find this addy in CSTK Holders in the TS xls)

![Screen Shot 2021-02-15 at 12.15.40 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/48ef7110-1116-4af6-aef4-b42496caedd6)

**Comment by GriffGreen** [comment]
![Screen Shot 2021-02-15 at 8.18.34 AM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/d14fe0fe-687c-4ff7-a2d9-732d89d1c76d)

This is a weird bug... cause Juan is on the registry....

**Comment by tamarandom** [comment]
Update : get Juan to share updates on what he is seeing now. Screenshot by screenshot to the issue if it still exists.

**Comment by tamarandom** [comment]
Closed! Juan Carlos no longer sees this error. He has paid his dues. All is good.
