### ISSUE TITLE
Minter doesn't allow making valid transaction

### ISSUE THREAD

**Issue by aminlatifi** [commons-stack/tech-dapp#175]
![image](https://user-images.githubusercontent.com/5684607/108128951-bfdf9780-70c2-11eb-83cf-31e6d4025175.png)

It's deposit method with this input
```
{
"homeTx":"0xef612283a9eff7386a8e3f27723d09261f56c616280950b3fea0f9a8959bcfa1",
"receiverId":"2349",
"token":"0x6B175474E89094C44Da98b954EedeAC495271d0F",
"amount":"1000000000000000000",
"sender":"0x839395e20bbB182fa440d08F850E6c7A8f6F0780"
}
```

**Comment by aminlatifi** [comment]
The same for 
```
{
  "homeTx": "0xf2fcdc68f7fe9cdf067c883c05da794d2ab703506a00a41ff4f6f564c90e97f8",
  "receiverId": "2349",
  "token": "0x6B175474E89094C44Da98b954EedeAC495271d0F",
  "amount": "450000000000000000000",
  "sender": "0x839395e20bbB182fa440d08F850E6c7A8f6F0780",
}
```

**Comment by aminlatifi** [comment]
@GriffGreen Says the cause is that user is over the limit and minter cannot mint token

**Comment by tamarandom** [comment]
Update : @aminlatifi  will add the two addresses to whom this happens (griff & simon) and then we close this. ;)

**Comment by GriffGreen** [comment]
These are the 2 addresses that are edge cases: 

0x839395e20bbB182fa440d08F850E6c7A8f6F0780
0x5b7575494b1e28974efe6EA71EC569b34958F72e

**Comment by tamarandom** [comment]
Lowering the priority as this is not a blocker to launching.

**Comment by tamarandom** [comment]
Update : edge case, closing.
