### ISSUE TITLE
Design elements on this screen 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/tech-dapp#176]
For the elements on the screen such as "pending score :",  should just that text be removed or do we do more to make it less redundant? ;) 

![photo_2021-02-17_12-44-37.jpg](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/d84f8d8f-67a5-4a44-89be-a4f7038f7c76)

**Comment by GriffGreen** [comment]
already designed... made a new issue
