### ISSUE TITLE
Remove the CSTK Token Balance from the upper box and move it to the lower box

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/tech-dapp#177]
![Screen Shot 2021-02-17 at 2.50.27 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/7b1a3a3c-67c7-4fcd-926e-71432b50a8d4)

Don't worry about the pending tx piece

**Comment by MerlinEgalite** [comment]
Hm what does it mean don't worry about the pending tx @GriffGreen ?
For now it's an amount of tokens not a transaction hash. What should I do?

**Comment by GriffGreen** [comment]
@MerlinEgalite 

The design screenshot has a pending tx piece.... don't worry about that, you can leave that feature out.... 

Just make the front end look like the picture... except for the pending transaction piece
