### ISSUE TITLE
Minimum should change if someone has paied dues already

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/tech-dapp#179]
![Screen Shot 2021-02-17 at 3.08.09 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/8ab9db52-a127-4d71-83b9-37fb3c7f6942)

If someone has paid dues (so their address is in our database), then the minimum should be 1 DAI

If someone has not paid dues, so they are not in our database of people who have paid, then the minimum should be 450.

**Comment by sponnet** [comment]
Right now the minimum is set to 900 - does that have to change back to 450 then ? @GriffGreen

**Comment by mendesfabio** [comment]
If the user didn't pay dues, the minimum is 450 DAI, else 1 DAI. Right, @GriffGreen?

**Comment by GriffGreen** [comment]
@sponnet  Default input is 900, thats not the min

If the user didn't pay dues, the minimum is 450 DAI, else 1 DAI. 

Right! @mendesfabio
