### ISSUE TITLE
CSTK score inM is 0 while CSTK score in dApp has a non-zero value

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/tech-dapp#185]
This might be confusing for members. Can someone explain why so that we have an answer at ready.  

![Screen Shot 2021-02-24 at 10.02.25 AM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/3a0b64ff-d100-4351-aa70-4e326dcb69f2)

**Comment by mendesfabio** [comment]
I think it happens because you're on Etherem Mainnet, but the CSTK tokens exist on the xDai blockchain.

**Comment by tamarandom** [comment]
Using the Add Metamask link worked (i.e., displayed token value in MM) when on the xDAI network.
