### ISSUE TITLE
Twitter & Telegram template

### ISSUE THREAD

**Issue by sponnet** [commons-stack/tech-dapp#188]
These popups still show a pretty dull tweet text

![image](https://user-images.githubusercontent.com/596726/109400238-d4842100-7947-11eb-86cb-51d5ea5f238b.png)

Any suggestion to make it better ? @GriffGreen

**Comment by tamarandom** [comment]
Absolutely! The final message is in #104

I've just become a member of Commons Stack's Swiss Association! 🎉🌍🌌🎩🥂 Join us: commonsstack.org/apply

Maybe we had it in more than one place? @mendesfabio is it OK if I assign this to you!?
