### ISSUE TITLE
Don't let the user select more Dai than they have and if they dont have 450 dont let them click the pay dues buttons

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/tech-dapp#195]
![Screen Shot 2021-03-05 at 12.01.57 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/41f1f242-b5a2-4e95-b92d-6202cfc32dec)

Suggested Logic:
If the person has >900 Dai
The default amount is 900 

If the person has 900-450 Dai
The default amount is the total amount of Dai 

If the person has less than 450 Dai, we autofill the box with 450 Dai but pop up a warning that says, "[Please obtain more Dai](https://1inch.exchange/#/r/0x8110d1D04ac316fdCACe8f24fD60C86b810AB15A) to pay memberships dues and join the Trusted Seed, if 450 Dai is a financial burden, please consider [applying for a scholarship](link to the blog post... eventually for now leave the link out as the blog post doesn't exist)"  

------Original bug report from Jeff-----

Was playing around with the Dapp again this morning and noticed some issues when I was testing out sending dues.  These may have already been raised by Kris in the other channel, but wanted to shoot you a screenshot quickly while it's top of mind.

Oh yeah, I just spent all my DAI on DEV for staking and stake.social for the Commons Stack.  Forgot about that! https://stakes.social/0xFa38Fc50e055CBE88Bd569eddCcE057999B2BC9C

Is it possible to throw a warning about insufficient DAI rather than transaction error and what looks like crazy gas fees?

**Comment by GriffGreen** [comment]
@MerlinEgalite @mendesfabio @sponnet First come first served! Assign yourself if you want it :-D

**Comment by MerlinEgalite** [comment]
Hey @GriffGreen do you have the link to the blog post please? 😊

**Comment by tamarandom** [comment]
Hey @MerlinEgalite -  not published yet. Soon! 

Though I have a diff comment regarding this, @GriffGreen. 

For this case, "If the person has 900-450 Dai, The default amount is the total amount of Dai", should we not instead set the default to 450 dai?  Here is why : the difference will be insufficient to fund a scholarship so there will be no message about what the additional dai will be used for. Which makes emptying the wallet a strange thing to experience. We could craft a new message but I'm thinking if there is less than 900 DAI, the default lands on the 450 dues owed.

**Comment by tamarandom** [comment]
Update : going with the max amount in the wallet if between 450 - 900. ;)
