### ISSUE TITLE
General Information / links

### ISSUE THREAD

**Issue by sponnet** [commons-stack/tech-dapp#42]
- [x] xDAI registry
- [x] xDAI CSTK token/minting contract
- [x] Link up React Dapp
- [x] link with Giveth campaign ( recipient address - campaign ID ) = donation
- [x] check admin permissions (can there be multiple minters ?? )
- [x] set up bridge (amin has done that?)
- [ ] set up connection to blockscout API

- [ ] How to update registry later on (probably through blockscout API)

![image](https://user-images.githubusercontent.com/596726/93260714-0d697880-f7a2-11ea-8882-52cd5f9a6039.png)

**Comment by GriffGreen** [comment]
Giveth Bridge Ethereum Address! 
https://etherscan.io/address/0x30f938fed5de6e06a9a7cd2ac3517131c317b1e7

Commons Stack Campaign (not really important just for reference) 
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e

Commons Stack xDAI DAO that Mints CSTK Tokens
https://aragon.1hive.org/?#/csdao/0xaa89fb730a83146cbf06661fd436e7445b4d0232/



CSTK Token Address
0xa18effbceb3b6bfd914bac1c08103fc93b5d4b45

Milestone to practice donating to:
https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5f37df764592e757ec626f7b
