### ISSUE TITLE
Create CSTK-phase token contracts

### ISSUE THREAD

**Issue by sponnet** [commons-stack/tech-dapp#5]
These contracts specify the 5 stages of contributing to CS.
There should be 4 contracts deployed.

## Phases / ratio
CSTK-1 | Token Engineering Commons | Augmented Bonding Curve | 2.5
CSTK-2 | Chosen by CSTK Token Holders | Giveth Proposal Engine | 2
CSTK-3 | Chosen by CSTK Token Holders | Conviction Voting | 1.5
CSTK-4 | Chosen by CSTK Token Holders | Analytics Dashboard | 1.25
CSTK-5 | Chosen by CSTK Token Holders | ‘Minimum Viable Commons’ | 1

Each contract should

- [ ] Implement ERC-20 interface
- [ ] Implement a ratio DAI - CSTK (2.5 , 2, ..)
- [ ] Have a function that claims DAI from `msg.sender` - forwards it to a vault address and mints CSTK-# tokens to a given destination address `for' - or to `msg.sender` if not specified.
- [ ] Have a soft-cap number ( expressed in CSTK-# token )
- [ ] Once the soft-cap has been exceeded - no refunds are possible any more
- [ ] Have a hard-cap address
- [ ] Once the hard-cap has been reached - it cannot mint more CSTK-# tokens
- [ ] Have a function the allows to send back the tokens - and return the DAI with the same ratio (only when soft-cap has not been exceeded)
- [ ] Have a start & stop functionality - only accessible by the contract owner (to start and stop phases)

## improved version

We could make it so that the next phase automatically opens up when the previous phase is completed (hard cap reached)
Therefor the contract needs the additional features:

- [ ] can whitelist an address that can call the 'start' function
- [ ] can have a destination address to trigger its 'start' function
- [ ] when the hard-cap has been reached - it automatically starts the next phase

## Even more improved version

- [ ] When next phase start is triggered , it could spend the remaining DAI and mint tokens to the `for` address

**Comment by paxthemax** [comment]
Are `CSTK-#` tokens transferable (ERC-20)? Or are they bound to the claimant's address, and can only be returned?

**Comment by paxthemax** [comment]
We should move this issue over to [https://github.com/commons-stack/tech-token](the tech token repo).
