### ISSUE TITLE
Testing!!! Ropsten DAI!! 

### ISSUE THREAD

**Issue by katzcaban** [commons-stack/tech-dapp#55]
Test using team addresses, make issues, trial and error

**Comment by sponnet** [comment]
Test URL : https://develop--tech-dapp.netlify.app/
Live URL :  https://member.commonsstack.foundation/

**Comment by tamarandom** [comment]
Hey @katzcaban ! Is this one ready to close? Or is there anything else left to do?

**Comment by katzcaban** [comment]
More testing has been done and if needed we can do additional testing after changes are made with developers today.
