### ISSUE TITLE
Whitelisting contract

### ISSUE THREAD

**Issue by sponnet** [commons-stack/tech-dapp#6]
For the whitelisting we should read it out of a contract

This contract should

- [ ] contain an owner address that can manipulate the whitelist
- [ ] have a whitelist for `contributors` containing `address` `allowed` `spent` for any given address
- [ ] have a whitelist for `CSTK-# contracts` that can manipulate the `spent` amount for any `contributor`
- [ ] have a public function to read out `spent` for a given address

**Comment by GriffGreen** [comment]
A few things:

The entire contract should be owned by the multisig... and then there should be a whitelist authority account that can change the `allowed` for any address

Not sure what "Spent" is used for exactly... so i could be off here. But I would think the balance of CSTK tokens in the account is the equivalent of Spent, and then there can be a check after the transfer of `require(tokenRecipient.balance<=allowed)` or something like that and that Spent is not needed... unless I am missing the value of the use of Spent, or an issue with that approach... 

Allowed (and spent) should have the units of CSTK tokens.

**Comment by sponnet** [comment]
My initial thought here was that `allowed` and `spent` would be the denomination in Dai - since on each contribution you will have to calculate the exchange rate & adjust the `spent` accordingly during a purchase of CSTK tokens. Imo it will be easier to track it this way + the allowed amount on the whitelist starts from the amount of DAI you can spend , not the amount of CSTK tokens you can receive.
Would you agree ?

**Comment by DaLN** [comment]
So far i have something like this :
```solidity
pragma solidity ^0.6.4;

import "@openzeppelin/contracts/ownership/Ownable.sol";

contract RegistryInterface is Ownable {
    constructor(address _owner, address _adminAddress) internal Ownable() {
        VERSIONS.push(1);

        owner = _owner;
        adminAddress = _adminAddress;
    }

    event ContributorAdded(address _contributor, address _sender);
    event ContributorRemoved(address _contributor, address _sender);

    event AdminKeyChanged(
        address _previousAdmin,
        address _newAdmin,
        address _sender
    );

    struct ContributorInfo {
        address wallet;
        uint256 allowed;
    }

    modifier onlyAdmin() {
        require(msg.sender == adminAddress);
        _;
    }

    modifier onlyAdminOrOwner() {
        require((msg.sender == adminAddress) || (msg.sender == owner));
        _;
    }

    function setAdminAddress(address _adminAddress) public onlyAdminOrOwner;

    function registerContributors(address[] wallets) public onlyAdmin returns (bool);

    function removeContributors(address[] wallets) public onlyAdmin returns (bool);

    function getContributor(address _address) public view 
        returns (address wallet, uint256 allowed);

    function getAllowed(address wallet) public view returns (uint256 allowed);

    function isContributor(address wallet) public view returns (bool);
}```

Removed spent for now.

**Comment by DaLN** [comment]
> My initial thought here was that `allowed` and `spent` would be the denomination in Dai - since on each contribution you will have to calculate the exchange rate & adjust the `spent` accordingly during a purchase of CSTK tokens. Imo it will be easier to track it this way + the allowed amount on the whitelist starts from the amount of DAI you can spend , not the amount of CSTK tokens you can receive.
> Would you agree ?

oh good point, allowed correspond to the maximum amount of DAI that a wallet can fund, but then the amount of CSTK or rCSTK depends on at which stage they invested, right ?

**Comment by DaLN** [comment]
>     * have a whitelist for `CSTK-# contracts` that can manipulate the `spent` amount for any `contributor`

So a list of contracts would be allowed to update the spent of the contributors, right ?

**Comment by GriffGreen** [comment]
> My initial thought here was that `allowed` and `spent` would be the denomination in Dai - since on each contribution you will have to calculate the exchange rate & adjust the `spent` accordingly during a purchase of CSTK tokens. Imo it will be easier to track it this way + the allowed amount on the whitelist starts from the amount of DAI you can spend , not the amount of CSTK tokens you can receive.
> Would you agree ?

Sadly we want to limit the number of CSTK tokens people can have... that is the desired utility of the list.

**Comment by paxthemax** [comment]
@DaLN I like the way OpenZeppelin handles it in their Role system. So:

- Multiple admins supported
- First admin is `owner` or passed via constructor
- Admins can `addAdmin` so someone can become admin
- Each individual admin can `renounceAdmin` to not be admin

Optional: owner can `removeAdmin` on any admin.

**Comment by GriffGreen** [comment]
I would be down with the `removeAdmin` option
basically the Commons Stack Org Multisig should be able to add and remove admins

**Comment by paxthemax** [comment]
This issue should be migrated to the appropriate [tech-token repo](https://github.com/commons-stack/tech-token)
